# Generated by Django 3.1.5 on 2021-01-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('classes', models.CharField(blank=True, max_length=200)),
                ('style', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('classes', models.CharField(blank=True, max_length=200)),
                ('style', models.TextField(blank=True)),
                ('extra_attrs', models.TextField(blank=True)),
                ('sorting', models.IntegerField(db_index=True, default=0, verbose_name='Sort')),
                ('elements', models.ManyToManyField(blank=True, to='page.Element')),
                ('sub_block', models.ManyToManyField(blank=True, related_name='sub_blocks', to='page.Block')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'block',
                'ordering': ['-sorting'],
            },
        ),
    ]
