# Generated by Django 3.1.5 on 2021-01-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210118_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='sub_block',
            field=models.ManyToManyField(blank=True, related_name='root', to='page.Block'),
        ),
    ]
