# Generated by Django 3.1.5 on 2021-01-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='id_attr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
