# Generated by Django 3.1.5 on 2021-01-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_block_id_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='extra_attrs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
