# Generated by Django 3.1.5 on 2021-01-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_element_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
