# Generated by Django 3.1.5 on 2021-01-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_block_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='classes',
        ),
    ]
