# Generated by Django 3.1.5 on 2021-01-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_remove_element_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='sorting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
